# Common system settings for all hosts
timezone: "Europe/Berlin"

# PostgreSQL configuration
postgresql_version: "14"
postgresql_encoding: "UTF-8"
postgresql_locale: "en_US.UTF-8"
postgresql_database: "devops_lab"
postgresql_user: "lab_user"
postgresql_password: "lab_password"  # Obviously, use something secure like Ansible Vault in production!

# Docker configuration
docker_compose_version: "2.17.2"

# Flask web app settings
app_name: "devops_lab"
app_port: 5000 # Flask default port
app_env: "development"
flask_secret_key: "super_secret_key_change_in_production" # Obviusly, use something secure in production!

# Docker container configuration
nginx_port: 80 # Nginx reverse proxy port
flask_container_name: "flask_app"
nginx_container_name: "nginx_proxy"
docker_network_name: "webapp_network"
